<?php

declare(strict_types=1);

return [
	'routes' => [
		['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
		['name' => 'page#index', 'url' => '/projects/{id}', 'verb' => 'GET', 'postfix' => 'project'],
		['name' => 'page#index', 'url' => '/versions/{id}', 'verb' => 'GET', 'postfix' => 'version'],
		['name' => 'page#index', 'url' => '/compare/{a}/{b}', 'verb' => 'GET', 'postfix' => 'compare'],
		['name' => 'media#attachment', 'url' => '/attachments/{id}', 'verb' => 'GET'],
		['name' => 'media#show', 'url' => '/versions/{id}/media/{kind}', 'verb' => 'GET'],
		['name' => 'export#download', 'url' => '/versions/{id}/export/{format}', 'verb' => 'GET'],
		['name' => 'export#liveSet', 'url' => '/versions/{id}/export/ableton', 'verb' => 'POST'],
		// Behind a Share Link. The {token} parameter lets the public-share
		// middleware check the share's password and expiry (ADR 0004).
		['name' => 'Public#showShare', 'url' => '/s/{token}', 'verb' => 'GET'],
		['name' => 'Public#showVersion', 'url' => '/s/{token}/versions/{versionId}', 'verb' => 'GET'],
		['name' => 'Public#showAuthenticate', 'url' => '/s/{token}/authenticate/{redirect}', 'verb' => 'GET'],
		['name' => 'Public#authenticate', 'url' => '/s/{token}/authenticate/{redirect}', 'verb' => 'POST'],
		['name' => 'PublicApi#context', 'url' => '/s/{token}/api/context', 'verb' => 'GET'],
		['name' => 'PublicApi#assets', 'url' => '/s/{token}/api/assets', 'verb' => 'GET'],
		['name' => 'PublicApi#media', 'url' => '/s/{token}/media/{versionId}/{kind}', 'verb' => 'GET'],
		['name' => 'PublicApi#settings', 'url' => '/s/{token}/api/reviewer', 'verb' => 'PUT'],
		['name' => 'PublicApi#claim', 'url' => '/s/{token}/api/reviewer', 'verb' => 'POST'],
		['name' => 'PublicApi#index', 'url' => '/s/{token}/api/versions/{versionId}/comments', 'verb' => 'GET'],
		['name' => 'PublicApi#create', 'url' => '/s/{token}/api/versions/{versionId}/comments', 'verb' => 'POST'],
		['name' => 'PublicApi#changes', 'url' => '/s/{token}/api/versions/{versionId}/changes', 'verb' => 'GET'],
		['name' => 'PublicApi#approve', 'url' => '/s/{token}/api/versions/{versionId}/approval', 'verb' => 'PUT'],
		['name' => 'PublicApi#seen', 'url' => '/s/{token}/api/versions/{versionId}/seen', 'verb' => 'POST'],
		['name' => 'PublicApi#update', 'url' => '/s/{token}/api/comments/{id}', 'verb' => 'PUT'],
		['name' => 'PublicApi#react', 'url' => '/s/{token}/api/comments/{id}/reactions', 'verb' => 'PUT'],
		['name' => 'PublicApi#attach', 'url' => '/s/{token}/api/comments/{id}/attachments', 'verb' => 'POST'],
		['name' => 'PublicApi#attachment', 'url' => '/s/{token}/attachments/{id}', 'verb' => 'GET'],
		['name' => 'PublicApi#destroy', 'url' => '/s/{token}/api/comments/{id}', 'verb' => 'DELETE'],
	],
	'ocs' => [
		['name' => 'project_api#index', 'url' => '/api/v1/projects', 'verb' => 'GET'],
		['name' => 'project_api#create', 'url' => '/api/v1/projects', 'verb' => 'POST'],
		['name' => 'project_api#byFolder', 'url' => '/api/v1/folders/{folderId}/project', 'verb' => 'GET'],
		['name' => 'project_api#show', 'url' => '/api/v1/projects/{id}', 'verb' => 'GET'],
		['name' => 'project_api#update', 'url' => '/api/v1/projects/{id}', 'verb' => 'PUT'],
		['name' => 'project_api#destroy', 'url' => '/api/v1/projects/{id}', 'verb' => 'DELETE'],
		['name' => 'project_api#members', 'url' => '/api/v1/projects/{id}/members', 'verb' => 'GET'],
		['name' => 'project_api#mute', 'url' => '/api/v1/projects/{id}/mute', 'verb' => 'PUT'],
		['name' => 'share_api#inProject', 'url' => '/api/v1/projects/{id}/shares', 'verb' => 'GET'],
		['name' => 'share_api#updateReviewer', 'url' => '/api/v1/reviewers/{id}', 'verb' => 'PUT'],
		['name' => 'share_api#renewReviewerKey', 'url' => '/api/v1/reviewers/{id}/key', 'verb' => 'POST'],
		['name' => 'project_api#assetForFile', 'url' => '/api/v1/files/{fileId}/asset', 'verb' => 'GET'],
		['name' => 'project_api#enableFile', 'url' => '/api/v1/assets', 'verb' => 'POST'],
		['name' => 'project_api#updateAsset', 'url' => '/api/v1/assets/{id}', 'verb' => 'PUT'],
		['name' => 'project_api#disableAsset', 'url' => '/api/v1/assets/{id}', 'verb' => 'DELETE'],
		['name' => 'project_api#version', 'url' => '/api/v1/versions/{id}', 'verb' => 'GET'],
		['name' => 'project_api#updateVersion', 'url' => '/api/v1/versions/{id}', 'verb' => 'PUT'],
		['name' => 'project_api#stackVersion', 'url' => '/api/v1/versions/{id}/stack', 'verb' => 'POST'],
		['name' => 'project_api#unstackVersion', 'url' => '/api/v1/versions/{id}/unstack', 'verb' => 'POST'],
		['name' => 'project_api#regenerate', 'url' => '/api/v1/versions/{id}/regenerate', 'verb' => 'POST'],
		['name' => 'comment_api#index', 'url' => '/api/v1/versions/{versionId}/comments', 'verb' => 'GET'],
		['name' => 'comment_api#create', 'url' => '/api/v1/versions/{versionId}/comments', 'verb' => 'POST'],
		['name' => 'comment_api#changes', 'url' => '/api/v1/versions/{versionId}/changes', 'verb' => 'GET'],
		['name' => 'comment_api#approve', 'url' => '/api/v1/versions/{versionId}/approval', 'verb' => 'PUT'],
		['name' => 'comment_api#seen', 'url' => '/api/v1/versions/{versionId}/seen', 'verb' => 'POST'],
		['name' => 'comment_api#update', 'url' => '/api/v1/comments/{id}', 'verb' => 'PUT'],
		['name' => 'comment_api#destroy', 'url' => '/api/v1/comments/{id}', 'verb' => 'DELETE'],
		['name' => 'comment_api#react', 'url' => '/api/v1/comments/{id}/reactions', 'verb' => 'PUT'],
		['name' => 'comment_api#attach', 'url' => '/api/v1/comments/{id}/attachments', 'verb' => 'POST'],
		['name' => 'comment_api#resolve', 'url' => '/api/v1/comments/{id}/resolved', 'verb' => 'PUT'],
		['name' => 'admin_settings#show', 'url' => '/api/v1/admin/settings', 'verb' => 'GET'],
		['name' => 'admin_settings#update', 'url' => '/api/v1/admin/settings', 'verb' => 'PUT'],
		['name' => 'share_api#index', 'url' => '/api/v1/files/{fileId}/shares', 'verb' => 'GET'],
		['name' => 'share_api#create', 'url' => '/api/v1/files/{fileId}/shares', 'verb' => 'POST'],
		['name' => 'share_api#update', 'url' => '/api/v1/shares/{shareId}', 'verb' => 'PUT'],
		['name' => 'share_api#reviewers', 'url' => '/api/v1/shares/{shareId}/reviewers', 'verb' => 'GET'],
		['name' => 'share_api#invite', 'url' => '/api/v1/shares/{shareId}/reviewers', 'verb' => 'POST'],
	],
];
